# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-04 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190503_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='alt',
            new_name='title',
        ),
    ]
